  version: "3"
  services:
    openldap:
      image: osixia/openldap:latest
      ports:
        - 636:636
        - 389:389
      environment:
        LDAP_DOMAIN: "dexter.com.br"
        LDAP_ADMIN_PASSWORD: "4Linux"